[package]
name = "ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "FFI : integration Kotlin/Swift/C/C++ (cf. docs/004-workspace.md paragraphe 17)"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
jni = "0.21"
common = { path = "../common" }
vault = { path = "../vault" }
manifest = { path = "../manifest" }
